### ISSUE TITLE
[Question] What's the condition of this plugin.

### ISSUE THREAD

**Issue by XMB-7** [3C0D/obsidian-quick-plugin-switcher#1]
Recently I hoped to use this plugin for batch adding time delays for other plugins, but surprisingly found that it disappears on the obsidian plugin market and even the original repo disappears.

All I could find is this new repo, with no ideas what happened to the old one. Could you please inform me of the condition of this awesome plugin? Thanks.

**Comment by 3C0D** [comment]
I had a rough word (not an insult) to a member of the team. I think he was voluntary ignoring me, even after the right modifications. It was not the first time, I had 10 plugins. He reported me and without a warning my account was flagged by github, so nobody could see my repos anymore. They did the same on discord twice. I was trying to have an explanation. 
I saw some people asking for my plugins. One guy contacted me for easy toggle sidebar plugin, so I created a new repo. And I knew this one was important too. 
But honestly, I lost any motivation.

**Comment by 3C0D** [comment]
So this is not an official repo of course. But you can use Brat or a manual technic to install it anyway...

**Comment by XMB-7** [comment]
Sorry to hear about the situation you've faced. Life sometimes throws unexpected challenges our way, and we may face hardships that seem unfair or undeserved. While it's natural to feel discouraged, please know that your work with efforts has made a lot of positive impact on the Obsidian community. Conflicts and misunderstandings can happen in any collaborative environment, but they don't diminish the value of your contributions.

As Romain Rolland once said, "There is only one heroism in the world: to see the world as it is and to love it." Wish you take a short break to recharge and reflect, and thank you for the awesome plugin.

**Comment by 3C0D** [comment]
Thanks for your kind words. I accepted the situation without resentment and my responsibility in it. This situation opened my eyes about GitHub and some other big platforms, even if I already knew it before...
I personally think this world is an illusion in a big consciousness. So we live what we have to live at any moment. Time being an illusion...
The essence lies not in the experience, but in our consciousness of it. We can acknowledge the world's imperfections and, by embracing this awareness, stay anchored in truth. This mindful approach allows us to navigate through both deceptions and verities, maintaining our integrity in an often chaotic reality.
